/**
 * CpdDraftInbox — top-of-page card on CpdPage showing the clinician's
 * draft CPD activities (the ones auto-generated by the Postgres
 * lock_session_on_signoff trigger when a cpdEligible audit was signed).
 *
 * Each draft has a "Reflect & submit" button that opens a small modal
 * with the 3 mandatory reflective fields:
 *   • Reflective notes      (free text)
 *   • Benefit to patients   (free text)
 *   • GDC outcomes          (multi-select A/B/C/D)
 *
 * On submit, the backend validates (CHECK + trigger) and flips the row
 * draft → submitted. Once submitted, it disappears from this inbox and
 * shows up in the verifier's queue.
 *
 * Empty state: shows a quiet "No drafts" placeholder so the card is
 * collapsible-friendly and doesn't shout when there's nothing to do.
 */

import { useEffect, useState } from "react";
import { listMyDrafts, submitDraft } from "../../services/cpdActivities.api";

const GDC_OUTCOMES = [
  { value: "A", label: "A — Communication" },
  { value: "B", label: "B — Management & leadership" },
  { value: "C", label: "C — Maintenance & development of knowledge" },
  { value: "D", label: "D — Maintenance & development of skills" },
];

const formatDate = (iso) => {
  if (!iso) return "—";
  const d = new Date(iso);
  return d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
};

export function CpdDraftInbox({ onSubmitted }) {
  const [drafts,   setDrafts]   = useState([]);
  const [loading,  setLoading]  = useState(true);
  const [error,    setError]    = useState(null);
  const [active,   setActive]   = useState(null);   // the draft currently in the modal

  const load = async () => {
    try {
      setLoading(true); setError(null);
      const rows = await listMyDrafts();
      setDrafts(rows);
    } catch (e) {
      setError(e.message ?? "Could not load CPD drafts");
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => { load(); }, []);

  const handleSubmitted = () => {
    setActive(null);
    load();
    onSubmitted?.();
  };

  /* Loading state — skeleton-light, no spinner (cleaner for a card that
   * loads in well under 100ms). */
  if (loading) return null;

  /* Quiet empty state — no card at all when there are no drafts to act on. */
  if (!error && drafts.length === 0) return null;

  return (
    <>
      <div style={cardStyle}>
        <div style={headStyle}>
          <div>
            <div style={eyebrowStyle}>Drafts awaiting your reflection</div>
            <h3 style={titleStyle}>
              {drafts.length} CPD draft{drafts.length === 1 ? "" : "s"} ready to submit
            </h3>
            <p style={leadStyle}>
              Auto-generated from your completed audits. Add reflective notes and submit to
              count these hours toward your GDC cycle.
            </p>
          </div>
        </div>

        {error && (
          <div style={errorStyle}>
            <strong>Couldn't load drafts.</strong> {error}
          </div>
        )}

        <ul style={listStyle}>
          {drafts.map((d) => (
            <li key={d.id} style={rowStyle}>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={rowTitleStyle}>{d.activityTitle}</div>
                <div style={rowMetaStyle}>
                  {d.auditSession?.template?.regulatorPrimary && (
                    <span style={regChipStyle}>{d.auditSession.template.regulatorPrimary}</span>
                  )}
                  <span>{d.cpdHours} hr · {formatDate(d.activityDate)}</span>
                </div>
              </div>
              <button type="button" style={ctaStyle} onClick={() => setActive(d)}>
                Reflect &amp; submit
              </button>
            </li>
          ))}
        </ul>
      </div>

      {active && (
        <CpdReflectionModal
          draft={active}
          onCancel={() => setActive(null)}
          onSubmitted={handleSubmitted}
        />
      )}
    </>
  );
}

/* ─── Reflection modal ────────────────────────────────────────────────── */

function CpdReflectionModal({ draft, onCancel, onSubmitted }) {
  const [reflectiveNotes,   setReflectiveNotes]   = useState("");
  const [benefitToPatients, setBenefitToPatients] = useState("");
  const [gdcOutcomes,       setGdcOutcomes]       = useState(draft.gdcOutcomes ?? []);
  const [submitting, setSubmitting] = useState(false);
  const [error,      setError]      = useState(null);

  const toggleOutcome = (v) => setGdcOutcomes((prev) =>
    prev.includes(v) ? prev.filter((x) => x !== v) : [...prev, v]);

  const canSubmit =
    reflectiveNotes.trim().length > 0 &&
    benefitToPatients.trim().length > 0 &&
    gdcOutcomes.length > 0 &&
    !submitting;

  const handleSubmit = async () => {
    if (!canSubmit) return;
    try {
      setSubmitting(true); setError(null);
      await submitDraft(draft.id, {
        reflectiveNotes:    reflectiveNotes.trim(),
        benefitToPatients:  benefitToPatients.trim(),
        gdcOutcomes,
      });
      onSubmitted?.();
    } catch (e) {
      setError(e.message ?? "Submission failed");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div style={scrimStyle} onClick={onCancel}>
      <div style={modalStyle} onClick={(e) => e.stopPropagation()}>
        <header style={modalHeadStyle}>
          <div style={{ fontSize: 10, letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--primary)", fontWeight: 800 }}>
            Reflect &amp; submit · {draft.cpdHours} hr
          </div>
          <h3 style={{ margin: "4px 0 0", fontFamily: "var(--font-display)", fontSize: 17, fontWeight: 700 }}>
            {draft.activityTitle}
          </h3>
          <div style={{ fontSize: 12, color: "var(--on-surface-variant)", marginTop: 4 }}>
            Audit completed {formatDate(draft.activityDate)}
          </div>
        </header>

        <div style={modalBodyStyle}>
          {draft.learningNeed && (
            <div style={fieldGroupStyle}>
              <span style={prefilledHintStyle}>Pre-filled — Learning need</span>
              <div style={prefilledValueStyle}>{draft.learningNeed}</div>
            </div>
          )}
          {draft.relationToPractice && (
            <div style={fieldGroupStyle}>
              <span style={prefilledHintStyle}>Pre-filled — Relation to practice</span>
              <div style={prefilledValueStyle}>{draft.relationToPractice}</div>
            </div>
          )}

          <Field
            label="Reflective notes"
            required
            value={reflectiveNotes}
            onChange={setReflectiveNotes}
            placeholder="What did you learn / observe / change as a result?"
            multiline
          />
          <Field
            label="Benefit to patients"
            required
            value={benefitToPatients}
            onChange={setBenefitToPatients}
            placeholder="How will / does this improve patient care?"
            multiline
          />

          <div style={fieldGroupStyle}>
            <label style={labelStyle}>
              GDC outcomes <span style={{ color: "#c62828", marginLeft: 3 }}>*</span>
            </label>
            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              {GDC_OUTCOMES.map((o) => {
                const on = gdcOutcomes.includes(o.value);
                return (
                  <label key={o.value} style={{
                    ...checkRowStyle,
                    ...(on ? checkRowOnStyle : {}),
                  }}>
                    <input type="checkbox" checked={on} onChange={() => toggleOutcome(o.value)} />
                    <span>{o.label}</span>
                  </label>
                );
              })}
            </div>
          </div>

          {error && (
            <div style={{ ...errorStyle, marginTop: 6 }}>{error}</div>
          )}
        </div>

        <footer style={modalFootStyle}>
          <button type="button" style={cancelBtnStyle} onClick={onCancel} disabled={submitting}>
            Cancel
          </button>
          <button type="button" style={{ ...primaryBtnStyle, opacity: canSubmit ? 1 : 0.4 }}
            onClick={handleSubmit} disabled={!canSubmit}>
            {submitting ? "Submitting…" : "Submit for verification"}
          </button>
        </footer>
      </div>
    </div>
  );
}

function Field({ label, required, value, onChange, placeholder, multiline }) {
  return (
    <div style={fieldGroupStyle}>
      <label style={labelStyle}>
        {label}{required && <span style={{ color: "#c62828", marginLeft: 3 }}>*</span>}
      </label>
      {multiline ? (
        <textarea value={value} onChange={(e) => onChange(e.target.value)}
          placeholder={placeholder} rows={3} style={inputStyle} />
      ) : (
        <input type="text" value={value} onChange={(e) => onChange(e.target.value)}
          placeholder={placeholder} style={inputStyle} />
      )}
    </div>
  );
}

/* ─── Inline styles (CSS-Modules would mean another file for ~30 rules;
 *     these styles are page-local and short — inline is the right call.) */

const cardStyle = {
  background: "linear-gradient(135deg, color-mix(in srgb, var(--primary) 5%, var(--surface)), var(--surface))",
  border: "1px solid color-mix(in srgb, var(--primary) 25%, var(--outline-variant))",
  borderRadius: 14, padding: "18px 22px", marginBottom: 22,
  boxShadow: "0 2px 12px rgba(15, 23, 42, 0.04)",
};
const headStyle = { display: "flex", alignItems: "flex-start", marginBottom: 14 };
const eyebrowStyle = {
  fontSize: 10, letterSpacing: "0.08em", textTransform: "uppercase",
  fontWeight: 800, color: "var(--primary)",
};
const titleStyle = {
  margin: "4px 0 0", fontFamily: "var(--font-display)", fontSize: 17, fontWeight: 700, color: "var(--on-surface)",
};
const leadStyle = { fontSize: 12.5, color: "var(--on-surface-variant)", marginTop: 4, maxWidth: 620, lineHeight: 1.5 };
const errorStyle = {
  padding: 10, marginTop: 8,
  background: "color-mix(in srgb, #c62828 8%, transparent)",
  border: "1px solid color-mix(in srgb, #c62828 30%, transparent)",
  borderRadius: 8, color: "#b71c1c", fontSize: 12,
};
const listStyle = { listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 8 };
const rowStyle = {
  display: "flex", alignItems: "center", gap: 14, padding: 12,
  background: "var(--surface)", border: "1px solid var(--outline-variant)", borderRadius: 10,
};
const rowTitleStyle = { fontSize: 13, fontWeight: 700, color: "var(--on-surface)" };
const rowMetaStyle = {
  fontSize: 11.5, color: "var(--on-surface-variant)", marginTop: 4,
  display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap",
};
const regChipStyle = {
  padding: "2px 8px", background: "color-mix(in srgb, var(--primary) 10%, transparent)",
  color: "var(--primary)", borderRadius: 999, fontSize: 10.5, fontWeight: 600,
};
const ctaStyle = {
  appearance: "none", background: "var(--primary)", color: "var(--on-primary, white)",
  border: "none", padding: "8px 14px", borderRadius: 8, fontSize: 12.5, fontWeight: 700, cursor: "pointer",
  flexShrink: 0,
};

const scrimStyle = {
  position: "fixed", inset: 0, background: "rgba(15, 23, 42, 0.42)",
  display: "flex", alignItems: "center", justifyContent: "center",
  padding: "24px 16px", zIndex: 60, overflowY: "auto",
};
const modalStyle = {
  width: "100%", maxWidth: 560, background: "var(--surface)", borderRadius: 16,
  boxShadow: "0 24px 64px rgba(15, 23, 42, 0.24)",
  display: "flex", flexDirection: "column", maxHeight: "calc(100vh - 48px)",
};
const modalHeadStyle = { padding: "18px 22px 14px", borderBottom: "1px solid var(--outline-variant)" };
const modalBodyStyle = { padding: "18px 22px", overflowY: "auto", display: "flex", flexDirection: "column", gap: 16 };
const modalFootStyle = {
  display: "flex", gap: 10, padding: "14px 22px",
  borderTop: "1px solid var(--outline-variant)", justifyContent: "flex-end",
};
const fieldGroupStyle = { display: "flex", flexDirection: "column", gap: 6 };
const labelStyle = {
  fontSize: 11, letterSpacing: "0.04em", textTransform: "uppercase",
  fontWeight: 700, color: "var(--on-surface-variant)",
};
const inputStyle = {
  font: "inherit", fontSize: 13, padding: "9px 11px",
  border: "1px solid var(--outline-variant)", borderRadius: 8,
  background: "var(--surface)", color: "var(--on-surface)",
  resize: "vertical", fontFamily: "inherit",
};
const checkRowStyle = {
  display: "flex", alignItems: "center", gap: 8, padding: "8px 11px",
  border: "1px solid var(--outline-variant)", borderRadius: 8,
  fontSize: 12, cursor: "pointer",
};
const checkRowOnStyle = {
  borderColor: "var(--primary)",
  background: "color-mix(in srgb, var(--primary) 6%, transparent)",
};
const prefilledHintStyle = {
  fontSize: 10, letterSpacing: "0.04em", textTransform: "uppercase",
  fontWeight: 700, color: "var(--primary)",
};
const prefilledValueStyle = {
  fontSize: 12.5, color: "var(--on-surface-variant)",
  padding: "8px 11px", background: "var(--surface-low)",
  borderRadius: 8, borderLeft: "3px solid var(--primary)", fontStyle: "italic",
};
const cancelBtnStyle = {
  appearance: "none", background: "transparent",
  border: "1px solid var(--outline-variant)", padding: "9px 16px", borderRadius: 8,
  fontSize: 13, fontWeight: 600, color: "var(--on-surface)", cursor: "pointer",
};
const primaryBtnStyle = {
  appearance: "none", background: "var(--primary)", color: "var(--on-primary, white)",
  border: "none", padding: "10px 18px", borderRadius: 8,
  fontSize: 13, fontWeight: 700, cursor: "pointer",
};
