/**
 * Daily Logbooks — local mock template library.
 *
 * Same shape as auditTemplates.js so the existing AuditFormRunner can
 * render these without a second engine. Adds two new input_type values:
 *
 *   • numeric_threshold — a number field with `min` / `max` bounds.
 *                         Triggers a critical alert banner when the
 *                         entered value falls outside the range
 *                         (regulatory non-compliance, e.g. fridge temp).
 *   • text              — free-text note (e.g. cycle number, batch ID).
 *
 * `frequency` is informational metadata; the cards-grid renders it as
 * a badge and the cadence engine eventually drives schedule generation.
 *
 * `criticalThresholdMessage` is shown verbatim in the alert banner when
 * the value violates min/max — bespoke per question so the message can
 * reference the specific regulator + remediation action.
 */

export const LOGBOOK_TEMPLATES = [

  /* ─── 1. Autoclave 1 — daily parameter / foil test ─────────────────
   * Modal layout per brief: Autoclave ID, Cycle Number, Temperature,
   * Pressure + pass/fail chemical-indicator checks. Operator Signature
   * is added by the modal footer (not a per-question field). */
  {
    id:        "autoclave_daily",
    title:     "Autoclave 1 Parameter Check",
    focus:     "Daily autoclave cycle parameter log + chemical-indicator foil test.",
    frequency: "daily",
    regulatorPrimary: "HTM 01-05 Sec 6.27-6.45",
    version:   1,
    questions: [
      { id: "q_autoc_id",
        text: "Autoclave ID / serial number",
        input_type: "text",
        placeholder: "e.g. Autoclave-1 SN-A4823" },
      { id: "q_autoc_cycle",
        text: "Cycle number for today's load",
        input_type: "text",
        placeholder: "e.g. 2026-05-24-CYC-014" },
      { id: "q_autoc_temp",
        text: "Holding temperature reached (degC)",
        input_type: "numeric_threshold",
        min: 134, max: 137, unit: "degC",
        regulatorRef: "HTM 01-05 Sec 6.42",
        criticalThresholdMessage: "Holding temperature outside the 134-137 degC validated band. Withdraw the load + raise an engineer call-out before re-using." },
      { id: "q_autoc_pressure",
        text: "Chamber pressure reached (bar)",
        input_type: "numeric_threshold",
        min: 2.0, max: 2.4, unit: "bar",
        regulatorRef: "HTM 01-05 Sec 6.42",
        criticalThresholdMessage: "Pressure outside the 2.0-2.4 bar validated band. Cycle invalid; reprocess the load and book engineer attendance." },
      { id: "q_autoc_indicator",
        text: "Chemical indicator (foil test) changed colour correctly?",
        input_type: "pass_fail_na",
        regulatorRef: "HTM 01-05 Sec 6.30",
        failGuidance: "Quarantine the load; do not release for clinical use until investigated." },
      { id: "q_autoc_seals",
        text: "Pouches intact + no wet packs detected after cycle?",
        input_type: "pass_fail_na" },
    ],
  },

  /* ─── 2. Clinical Vaccine Fridge — temperature check ──────────────── */
  {
    id:        "vaccine_fridge_daily",
    title:     "Clinical Vaccine Fridge (Temperature Check)",
    focus:     "Twice-daily fridge temperature log + cold-chain integrity.",
    frequency: "daily",
    regulatorPrimary: "PHE Cold Chain Guidance",
    version:   1,
    questions: [
      { id: "q_fridge_01",
        text: "Current fridge temperature (degC)",
        input_type: "numeric_threshold",
        min: 2, max: 8, unit: "degC",
        regulatorRef: "PHE Cold Chain Guidance",
        criticalThresholdMessage: "CRITICAL OUT OF BOUNDS ALERT: Vaccine fridge temperature exceeds compliance limits. Notify the Practice Manager immediately." },
      { id: "q_fridge_02",
        text: "Minimum temperature since last check (degC)",
        input_type: "numeric_threshold",
        min: 2, max: 8, unit: "degC",
        regulatorRef: "PHE Cold Chain Guidance",
        criticalThresholdMessage: "Min temp breached cold-chain. Quarantine affected vaccines + contact supplier for advice." },
      { id: "q_fridge_03",
        text: "Maximum temperature since last check (degC)",
        input_type: "numeric_threshold",
        min: 2, max: 8, unit: "degC",
        regulatorRef: "PHE Cold Chain Guidance",
        criticalThresholdMessage: "Max temp breached cold-chain. Quarantine affected vaccines + contact supplier for advice." },
      { id: "q_fridge_04",
        text: "Fridge door seal visually intact + dedicated to clinical use only?",
        input_type: "pass_fail_na" },
      { id: "q_fridge_05",
        text: "Thermometer calibration certificate within 12 months?",
        input_type: "pass_fail_na",
        regulatorRef: "PHE Cold Chain Guidance" },
    ],
  },

  /* ─── 3. Decontamination Room — climate tracking ───────────────────── */
  {
    id:        "decon_climate_daily",
    title:     "Decontamination Room (Climate Tracking)",
    focus:     "Ambient temperature + humidity + ventilation check for the decon zone.",
    frequency: "daily",
    regulatorPrimary: "HTM 01-05 Sec 4.13",
    version:   1,
    questions: [
      { id: "q_decon_clim_01",
        text: "Ambient room temperature (degC)",
        input_type: "numeric_threshold",
        min: 18, max: 25, unit: "degC",
        regulatorRef: "HTM 01-05 Sec 4.13",
        criticalThresholdMessage: "Decon room ambient temperature outside 18-25 degC operating band. Review HVAC + delay reprocessing if humidity also out-of-spec." },
      { id: "q_decon_clim_02",
        text: "Relative humidity (%)",
        input_type: "numeric_threshold",
        min: 30, max: 60, unit: "%",
        criticalThresholdMessage: "Humidity outside 30-60% range affects packaging integrity. Engage maintenance + record affected loads." },
      { id: "q_decon_clim_03",
        text: "Extract ventilation operating + dirty-to-clean airflow direction verified?",
        input_type: "pass_fail_na",
        regulatorRef: "HTM 01-05 Sec 4.10" },
      { id: "q_decon_clim_04",
        text: "Setting room separation barrier in place (door / curtain closed)?",
        input_type: "pass_fail_na" },
      { id: "q_decon_clim_05",
        text: "Operator wearing correct PPE for the decon zone (visor + gloves + apron)?",
        input_type: "pass_fail_na" },
    ],
  },

  /* ─── 4. Foil Test — daily autoclave chemical indicator ───────────── */
  {
    id:        "foil_test_daily",
    title:     "Foil Test (Autoclave Chemical Indicator)",
    focus:     "Daily chemical-indicator foil + pouch integrity check per HTM 01-05.",
    frequency: "daily",
    regulatorPrimary: "HTM 01-05 Sec 6.30",
    version:   1,
    questions: [
      { id: "q_foil_01",
        text: "Autoclave ID / serial number used for today's foil test",
        input_type: "text",
        placeholder: "e.g. Autoclave-1 SN-A4823" },
      { id: "q_foil_02",
        text: "Cycle number / reference for the test load",
        input_type: "text",
        placeholder: "e.g. 2026-05-24-CYC-001" },
      { id: "q_foil_03",
        text: "Chemical indicator changed colour correctly across the foil?",
        input_type: "pass_fail_na",
        regulatorRef: "HTM 01-05 Sec 6.30",
        failGuidance: "Quarantine the load; raise an engineer call-out before re-using the autoclave." },
      { id: "q_foil_04",
        text: "All pouches intact with unbroken seals + no wet packs detected?",
        input_type: "pass_fail_na",
        regulatorRef: "HTM 01-05 Sec 6.32" },
      { id: "q_foil_05",
        text: "Printout / cycle log filed against today's date for the audit trail",
        input_type: "pass_fail_na" },
    ],
  },

  /* ─── 5. Medication / Material Fridge — daily temperature ─────────── */
  {
    id:        "medication_fridge_daily",
    title:     "Medication / Material Fridge (Temperature Check)",
    focus:     "Daily cold-chain log for the medication + materials fridge (separate from the clinical vaccine fridge).",
    frequency: "daily",
    regulatorPrimary: "MHRA Cold Storage Guidance",
    version:   1,
    questions: [
      { id: "q_medfridge_01",
        text: "Current fridge temperature (degC)",
        input_type: "numeric_threshold",
        min: 2, max: 8, unit: "degC",
        regulatorRef: "MHRA Cold Storage",
        criticalThresholdMessage: "Medication fridge outside 2-8 degC band. Quarantine affected stock + record action in the cold-chain log before continuing use." },
      { id: "q_medfridge_02",
        text: "Minimum temperature since last check (degC)",
        input_type: "numeric_threshold",
        min: 2, max: 8, unit: "degC",
        criticalThresholdMessage: "Min temperature breached. Inspect contents + contact supplier for affected medication advice." },
      { id: "q_medfridge_03",
        text: "Maximum temperature since last check (degC)",
        input_type: "numeric_threshold",
        min: 2, max: 8, unit: "degC",
        criticalThresholdMessage: "Max temperature breached. Inspect contents + contact supplier for affected medication advice." },
      { id: "q_medfridge_04",
        text: "Fridge interior clean + nothing expired on visual scan?",
        input_type: "pass_fail_na" },
      { id: "q_medfridge_05",
        text: "Door seal intact (no condensation / frosting)?",
        input_type: "pass_fail_na" },
    ],
  },

  /* ─── 6. Suction Line Flush — daily end-of-day ────────────────────── */
  {
    id:        "suction_line_daily",
    title:     "Suction Line Flush (End-of-Day)",
    focus:     "Daily suction line flush + amalgam separator visual per HTM 01-05 / HTM 07-01.",
    frequency: "daily",
    regulatorPrimary: "HTM 01-05 / HTM 07-01",
    version:   1,
    questions: [
      { id: "q_suction_01",
        text: "Suction lines flushed with manufacturer-approved cleaner at end of day?",
        input_type: "pass_fail_na",
        regulatorRef: "HTM 01-05 Sec 6.117",
        failGuidance: "Flush before leaving the site; record the chemical + dilution used." },
      { id: "q_suction_02",
        text: "Volume of cleaner used (mL) across all chairs",
        input_type: "numeric_threshold",
        min: 100, max: 2000, unit: "mL",
        criticalThresholdMessage: "Volume outside expected 100-2000 mL range. Confirm dosing system is functioning + log a maintenance ticket." },
      { id: "q_suction_03",
        text: "Amalgam separator visual: chamber level below the manufacturer's max line?",
        input_type: "pass_fail_na",
        regulatorRef: "EU Mercury Reg 2017/852",
        failGuidance: "Book a separator exchange + raise a hazardous-waste consignment note." },
      { id: "q_suction_04",
        text: "Filter trap inspected + emptied if required?",
        input_type: "pass_fail_na" },
      { id: "q_suction_05",
        text: "Operator initials + product batch used",
        input_type: "text",
        placeholder: "e.g. JD / Orotol Plus batch 2025-A14" },
    ],
  },

  /* ─── 7. Compressor & Scavenging — daily pressure log ─────────────── */
  {
    id:        "compressor_scavenging_daily",
    title:     "Compressor & Scavenging (Daily Check)",
    focus:     "Daily compressor pressure reading + scavenging visual for surgery readiness.",
    frequency: "daily",
    regulatorPrimary: "HSE PSSR / COSHH",
    version:   1,
    questions: [
      { id: "q_comp_01",
        text: "Compressor pressure at start of day (bar)",
        input_type: "numeric_threshold",
        min: 4, max: 8, unit: "bar",
        regulatorRef: "HSE PSSR",
        criticalThresholdMessage: "Compressor pressure outside 4-8 bar operating band. Do not start clinical sessions until engineer attends." },
      { id: "q_comp_02",
        text: "Receiver tank drained of condensate?",
        input_type: "pass_fail_na",
        failGuidance: "Drain immediately; persistent water can corrode the tank + invalidate the PSSR insurance." },
      { id: "q_comp_03",
        text: "No audible air leaks at couplings + compressor housing?",
        input_type: "pass_fail_na" },
      { id: "q_comp_04",
        text: "Scavenging system: active gas extraction confirmed at each surgery?",
        input_type: "pass_fail_na",
        regulatorRef: "COSHH (anaesthetic gases)" },
      { id: "q_comp_05",
        text: "Operator initials + any maintenance action raised",
        input_type: "text",
        placeholder: "e.g. JD / no action" },
    ],
  },

  /* ─── 8. Surgery Setup — daily open / close ───────────────────────── */
  {
    id:        "surgery_setup_daily",
    title:     "Surgery Setup (Daily Open / Close)",
    focus:     "Per-surgery open + close checklist: chair, A/C, instruments, biohazard.",
    frequency: "daily",
    regulatorPrimary: "CQC Reg 12 / HTM 01-05",
    version:   1,
    questions: [
      { id: "q_surg_01",
        text: "Surgery / room identifier",
        input_type: "text",
        placeholder: "e.g. Surgery 2 (Brighton)" },
      { id: "q_surg_02",
        text: "Dental chair tested + waterlines purged for 2 minutes before first patient?",
        input_type: "pass_fail_na",
        regulatorRef: "HTM 01-05 Sec 6.117" },
      { id: "q_surg_03",
        text: "Sharps bin in date + less than 3/4 full?",
        input_type: "pass_fail_na",
        regulatorRef: "HTM 07-01",
        failGuidance: "Replace immediately; do not start the clinical session with an overfull sharps bin." },
      { id: "q_surg_04",
        text: "All surfaces clean, decontaminated + clinical waste bag fresh?",
        input_type: "pass_fail_na" },
      { id: "q_surg_05",
        text: "Lighting, suction + handpieces tested + functional?",
        input_type: "pass_fail_na" },
      { id: "q_surg_06",
        text: "Closing operator signature + session number",
        input_type: "text",
        placeholder: "e.g. JD / PM session" },
    ],
  },

  /* ─── 9. Emergency Drug Kit Seal — daily visual ───────────────────── */
  {
    id:        "emergency_kit_seal_daily",
    title:     "Emergency Drug Kit (Daily Seal Check)",
    focus:     "Daily visual on the emergency kit + oxygen cylinder readiness (separate from the monthly contents audit).",
    frequency: "daily",
    regulatorPrimary: "GDC Standards 6.6 / Resuscitation Council UK",
    version:   1,
    questions: [
      { id: "q_emerg_01",
        text: "Emergency drug kit tamper seal intact (no opening since last check)?",
        input_type: "pass_fail_na",
        regulatorRef: "Resuscitation Council UK",
        failGuidance: "Run the full monthly contents audit before next patient session + log who broke the seal." },
      { id: "q_emerg_02",
        text: "Oxygen cylinder pressure reading (bar)",
        input_type: "numeric_threshold",
        min: 50, max: 200, unit: "bar",
        criticalThresholdMessage: "Oxygen cylinder reading below 50 bar (or above 200). Replace before next clinical session; do not begin treatment without a usable cylinder." },
      { id: "q_emerg_03",
        text: "AED battery + pad status indicator showing ready?",
        input_type: "pass_fail_na",
        failGuidance: "Swap in a spare; book a service for the affected unit." },
      { id: "q_emerg_04",
        text: "Kit accessible from all clinical areas (no blockages / locked doors)?",
        input_type: "pass_fail_na" },
      { id: "q_emerg_05",
        text: "Operator initials",
        input_type: "text",
        placeholder: "e.g. JD" },
    ],
  },

  /* ─── 10. Waterline Dipslides — microbiological count (WEEKLY) ────── */
  {
    id:        "waterline_dipslides_weekly",
    title:     "Waterline Dipslides (Microbiological Count)",
    focus:     "Weekly DUWL CFU dip-slide test + shock-dose verification.",
    frequency: "weekly",
    regulatorPrimary: "HTM 01-05 Sec 6.122",
    version:   1,
    questions: [
      { id: "q_water_dip_01",
        text: "CFU count from dip-slide reading (per mL)",
        input_type: "numeric_threshold",
        min: 0, max: 200, unit: "CFU/mL",
        regulatorRef: "HTM 01-05 Sec 6.122",
        criticalThresholdMessage: "CFU/mL count exceeds the HTM 01-05 limit of 200 CFU/mL. Withdraw line from clinical use, shock-treat the system, repeat dipslide before service resumption." },
      { id: "q_water_dip_02",
        text: "Dipslide incubated for the manufacturer-specified period at correct temperature?",
        input_type: "pass_fail_na" },
      { id: "q_water_dip_03",
        text: "Disinfectant dose level (PPM as documented in SOP)",
        input_type: "text",
        placeholder: "e.g. 200 PPM (Bioblast)" },
      { id: "q_water_dip_04",
        text: "Independent water-bottle delivery system (no mains-fed lines)?",
        input_type: "pass_fail_na",
        regulatorRef: "HTM 01-05 Sec 6.117" },
      { id: "q_water_dip_05",
        text: "Operator competency for dipslide handling current + signed off?",
        input_type: "pass_fail_na" },
    ],
  },

  /* ─── 11. Protein Residue Test — weekly ninhydrin verification ────── */
  {
    id:        "protein_residue_weekly",
    title:     "Protein Residue Test",
    focus:     "Weekly ninhydrin protein-residue test on a representative instrument to verify cleaning efficacy.",
    frequency: "weekly",
    regulatorPrimary: "HTM 01-05 Sec 6.50",
    version:   1,
    questions: [
      { id: "q_prot_01",
        text: "Instrument tested (ID / type)",
        input_type: "text",
        placeholder: "e.g. Mirror set #3" },
      { id: "q_prot_02",
        text: "Test kit lot number",
        input_type: "text",
        placeholder: "e.g. NIN-2025-A14" },
      { id: "q_prot_03",
        text: "Result reading (ug/cm2)",
        input_type: "numeric_threshold",
        min: 0, max: 3, unit: "ug/cm2",
        regulatorRef: "HTM 01-05 Sec 6.50",
        criticalThresholdMessage: "Result exceeds 3 ug/cm2 cleaning threshold. Re-process the load + investigate washer-disinfector cycle parameters." },
      { id: "q_prot_04",
        text: "Test kit within expiry date?",
        input_type: "pass_fail_na" },
      { id: "q_prot_05",
        text: "Instrument visually clean before test (no debris)?",
        input_type: "pass_fail_na" },
    ],
  },

  /* ─── 12. Soil Test (PCD) — weekly washer-disinfector challenge ───── */
  {
    id:        "soil_test_weekly",
    title:     "Soil Test",
    focus:     "Weekly process challenge device (PCD) test to validate washer-disinfector cleaning performance.",
    frequency: "weekly",
    regulatorPrimary: "HTM 01-05 Sec 6.48",
    version:   1,
    questions: [
      { id: "q_soil_01",
        text: "Washer-disinfector ID used for the test",
        input_type: "text",
        placeholder: "e.g. WD-1 SN-W2199" },
      { id: "q_soil_02",
        text: "Cycle number / printout reference",
        input_type: "text",
        placeholder: "e.g. 2026-05-24-WD-CYC-008" },
      { id: "q_soil_03",
        text: "Thermal disinfection temperature reached (degC)",
        input_type: "numeric_threshold",
        min: 80, max: 95, unit: "degC",
        regulatorRef: "HTM 01-05 Sec 6.48",
        criticalThresholdMessage: "Temperature outside the 80-95 degC disinfection band. Cycle invalid; reprocess + raise engineer call-out." },
      { id: "q_soil_04",
        text: "Test soil completely removed from the PCD?",
        input_type: "pass_fail_na",
        failGuidance: "Quarantine the load; treat as cleaning failure and re-run cycle once root cause identified." },
      { id: "q_soil_05",
        text: "Cycle printout / log filed for the audit trail?",
        input_type: "pass_fail_na" },
    ],
  },
];

export function getLogbookTemplate(id) {
  return LOGBOOK_TEMPLATES.find((t) => t.id === id) ?? null;
}
