import { isDemoMode } from "../lib/demoMode.js";
const leaveDefaults = {
  annualLeaveEntitlement: 25,
  usedLeaveDays: 0,
  remainingLeaveDays: 25,
  sickLeaveEntitlement: 10,
  usedSickDays: 0,
  remainingSickDays: 10,
  isTempPassword: false,
};

// Demo authentication exists only in Vite development builds. Production
// profiles retain their display data for the mocked UI, but carry no password.
const demoPassword = (username) => (isDemoMode() ? username : undefined);

const makeProfile = (jobTitle, location = "Group Support") => ({
  jobTitle,
  joinDate: "April 8th, 2024",
  contract: "Full-Time (Permanent)",
  location,
  annualLeaveBalance: 25,
});

const fullDocs = { gdcCertificate: true, indemnity: true, dbs: true };
const adminDocs = { gdcCertificate: null, indemnity: null, dbs: true };

export const demoUsers = [
  {
    id: "company-owner",
    username: "o",
    password: demoPassword("o"),
    role: "companyOwner",
    staffId: 1,
    managerId: null,
    scopeType: "global",
    scopeIds: ["all"],
    displayName: "Olivia Owner",
    ...leaveDefaults,
    hrProfile: makeProfile("Company Owner", "Executive Office"),
    email: "olivia.owner@verbilo.co.uk",
    phoneExtension: "101",
    dateOfBirth: "1978-05-12",
    gender: "female",
    startDate: "2014-01-06",
    bio: "Founded the group in 2014 with a single practice and a clear vision: blend exceptional clinical care with a workplace where people actually want to come to work. Now oversees six practices across two areas.",
    qualifications: ["MBA Business Leadership", "Diploma in Healthcare Management"],
    languages: ["English", "Italian"],
    documents: adminDocs,
    isOnline: true,
  },
  {
    id: "left-hand",
    username: "lh",
    password: demoPassword("lh"),
    role: "chiefOfStaff",
    staffId: 2,
    managerId: "company-owner",
    scopeType: "global",
    scopeIds: ["all"],
    displayName: "Lena Hart",
    ...leaveDefaults,
    hrProfile: makeProfile("Owner's Left-Hand / Chief of Staff", "Executive Office"),
    email: "lena.hart@verbilo.co.uk",
    phoneExtension: "102",
    dateOfBirth: "1984-09-21",
    gender: "female",
    startDate: "2018-03-04",
    bio: "Chief of Staff and the owner's strategic partner. Runs board reporting, cross-area projects, and the long-term plan.",
    qualifications: ["BA (Hons) Business & Management"],
    languages: ["English", "French"],
    documents: adminDocs,
    isOnline: true,
  },
  {
    id: "right-hand",
    username: "rh",
    password: demoPassword("rh"),
    role: "operationsDirector",
    staffId: 3,
    managerId: "company-owner",
    scopeType: "global",
    scopeIds: ["all"],
    displayName: "Ryan Hale",
    ...leaveDefaults,
    hrProfile: makeProfile("Owner's Right-Hand / Operations Director", "Executive Office"),
    email: "ryan.hale@verbilo.co.uk",
    phoneExtension: "103",
    dateOfBirth: "1981-11-02",
    gender: "male",
    startDate: "2017-09-11",
    bio: "Operations Director. Owns rotas, supplier contracts, and the day-to-day mechanics that keep every site humming.",
    qualifications: ["MSc Operations Management"],
    languages: ["English"],
    documents: adminDocs,
    isOnline: false,
  },
  {
    id: "managers-manager",
    username: "m.m",
    password: demoPassword("m.m"),
    role: "secondInCharge",
    staffId: 4,
    managerId: "company-owner",
    scopeType: "global",
    scopeIds: ["all"],
    displayName: "Morgan Senior Manager",
    ...leaveDefaults,
    hrProfile: makeProfile("Second in Charge", "Multi-Site"),
    email: "morgan.senior@verbilo.co.uk",
    phoneExtension: "104",
    dateOfBirth: "1986-07-18",
    gender: "prefer-not-to-say",
    startDate: "2019-06-17",
    bio: "Second in Charge across both areas. The link between the executive office and the area managers in the field.",
    qualifications: ["BA (Hons) Business Administration"],
    languages: ["English", "Spanish"],
    documents: adminDocs,
    isOnline: true,
  },
  {
    id: "area-manager-1",
    username: "a1",
    password: demoPassword("a1"),
    role: "areaManager",
    staffId: 5,
    managerId: "managers-manager",
    scopeType: "area",
    scopeIds: ["area-1"],
    areaId: "area-1",
    displayName: "Aisha Area One",
    ...leaveDefaults,
    hrProfile: makeProfile("Area Manager - Area 1", "Southall, Reading, New Cross"),
    email: "aisha.area@verbilo.co.uk",
    phoneExtension: "201",
    dateOfBirth: "1989-02-14",
    gender: "female",
    startDate: "2020-04-06",
    bio: "Area Manager for Area 1 (Southall, Reading, New Cross). Visits each site weekly and is the practice managers' first call.",
    qualifications: ["BA Business Management"],
    languages: ["English", "Hindi", "Urdu"],
    documents: adminDocs,
    isOnline: true,
  },
  {
    id: "manager",
    username: "m",
    password: demoPassword("m"),
    role: "practiceManager",
    staffId: 6,
    managerId: "area-manager-1",
    scopeType: "practice",
    scopeIds: ["practice-harley"],
    areaId: "area-1",
    practiceId: "practice-harley",
    displayName: "Maya Manager",
    ...leaveDefaults,
    hrProfile: makeProfile("Practice Manager", "Southall"),
    email: "maya.manager@verbilo.co.uk",
    phoneExtension: "210",
    dateOfBirth: "1990-08-05",
    gender: "female",
    startDate: "2021-01-11",
    bio: "Practice Manager at Southall. Owns the rota, patient feedback, and team development at site level.",
    qualifications: ["Level 4 Dental Practice Management"],
    languages: ["English", "Gujarati"],
    documents: adminDocs,
    isOnline: true,
  },
  {
    id: "deputy-practice-manager",
    username: "dpm",
    password: demoPassword("dpm"),
    role: "deputyPracticeManager",
    staffId: 7,
    managerId: "manager",
    scopeType: "practice",
    scopeIds: ["practice-harley"],
    areaId: "area-1",
    practiceId: "practice-harley",
    displayName: "Dev Patel",
    ...leaveDefaults,
    hrProfile: makeProfile("Deputy Practice Manager", "Southall"),
    email: "dev.patel@verbilo.co.uk",
    phoneExtension: "211",
    dateOfBirth: "1992-10-28",
    gender: "male",
    startDate: "2022-08-22",
    bio: "Deputy Practice Manager at Southall. Day-to-day floor lead and Maya's right hand on staff scheduling.",
    qualifications: ["Level 3 Dental Practice Administration"],
    languages: ["English", "Hindi"],
    documents: adminDocs,
    isOnline: false,
  },
  {
    id: "clinical-lead",
    username: "cl",
    password: demoPassword("cl"),
    role: "clinicalLead",
    staffId: 8,
    managerId: "manager",
    scopeType: "team",
    scopeIds: ["team-clinical-harley"],
    areaId: "area-1",
    practiceId: "practice-harley",
    teamId: "team-clinical-harley",
    displayName: "Dr. Callum Lead",
    ...leaveDefaults,
    hrProfile: makeProfile("Clinical Lead", "Southall"),
    email: "callum.lead@verbilo.co.uk",
    phoneExtension: "220",
    dateOfBirth: "1983-04-30",
    gender: "male",
    startDate: "2019-09-02",
    gdcNumber: "248113",
    gdcType: "Dentist",
    gdcRenewal: "2026-12-31",
    bio: "Clinical Lead at Southall. Heads the clinical team and signs off on complex treatment planning.",
    qualifications: ["BDS (Hons) King's College London", "MFDS RCS (Eng)", "PG Cert Implantology"],
    languages: ["English", "French"],
    documents: fullDocs,
    isOnline: true,
  },
  {
    id: "lead-nurse",
    username: "ln",
    password: demoPassword("ln"),
    role: "leadNurse",
    staffId: 9,
    managerId: "clinical-lead",
    scopeType: "team",
    scopeIds: ["team-nursing-harley"],
    areaId: "area-1",
    practiceId: "practice-harley",
    teamId: "team-nursing-harley",
    displayName: "Nina Nurse Lead",
    ...leaveDefaults,
    hrProfile: makeProfile("Lead Nurse", "Southall"),
    email: "nina.nurse@verbilo.co.uk",
    phoneExtension: "221",
    dateOfBirth: "1988-12-09",
    gender: "female",
    startDate: "2018-05-14",
    gdcNumber: "172604",
    gdcType: "Dental Nurse",
    gdcRenewal: "2026-07-31",
    bio: "Lead Nurse at Southall. Manages the nursing rota, sterilisation compliance, and infection control audits.",
    qualifications: ["NEBDN National Diploma", "Post-Reg Cert in Oral Health Education"],
    languages: ["English", "Polish"],
    documents: fullDocs,
    isOnline: true,
  },
  {
    id: "dental-nurse",
    username: "dn",
    password: demoPassword("dn"),
    role: "dentalNurse",
    staffId: 10,
    managerId: "lead-nurse",
    scopeType: "self",
    scopeIds: ["dental-nurse"],
    areaId: "area-1",
    practiceId: "practice-harley",
    teamId: "team-nursing-harley",
    displayName: "Daisy Nurse",
    ...leaveDefaults,
    hrProfile: makeProfile("Dental Nurse", "Southall"),
    email: "daisy.nurse@verbilo.co.uk",
    phoneExtension: "222",
    dateOfBirth: "1995-06-17",
    gender: "female",
    startDate: "2023-02-13",
    gdcNumber: "298110",
    gdcType: "Dental Nurse",
    gdcRenewal: "2026-07-31",
    bio: "Dental Nurse at Southall. Works primarily with the implant and orthodontics team.",
    qualifications: ["NEBDN National Diploma"],
    languages: ["English"],
    documents: fullDocs,
    isOnline: false,
  },
  {
    id: "front-of-house-lead",
    username: "foh",
    password: demoPassword("foh"),
    role: "frontOfHouseLead",
    staffId: 11,
    managerId: "manager",
    scopeType: "team",
    scopeIds: ["team-front-house-harley"],
    areaId: "area-1",
    practiceId: "practice-harley",
    teamId: "team-front-house-harley",
    displayName: "Freya Front",
    ...leaveDefaults,
    hrProfile: makeProfile("Front of House Lead", "Southall"),
    email: "freya.front@verbilo.co.uk",
    phoneExtension: "230",
    dateOfBirth: "1991-03-24",
    gender: "female",
    startDate: "2020-10-19",
    bio: "Front of House Lead at Southall. First face patients see and the calm in the morning rush.",
    qualifications: ["Level 3 Customer Service"],
    languages: ["English", "Portuguese"],
    documents: adminDocs,
    isOnline: true,
  },
  {
    id: "receptionist",
    username: "rec",
    password: demoPassword("rec"),
    role: "receptionist",
    staffId: 12,
    managerId: "front-of-house-lead",
    scopeType: "self",
    scopeIds: ["receptionist"],
    areaId: "area-1",
    practiceId: "practice-harley",
    teamId: "team-front-house-harley",
    displayName: "Ria Reception",
    ...leaveDefaults,
    hrProfile: makeProfile("Receptionist", "Southall"),
    email: "ria.reception@verbilo.co.uk",
    phoneExtension: "231",
    dateOfBirth: "1998-01-08",
    gender: "female",
    startDate: "2023-07-03",
    bio: "Receptionist at Southall. Owns the front desk and patient bookings.",
    qualifications: ["Level 2 Business Administration"],
    languages: ["English"],
    documents: adminDocs,
    isOnline: true,
  },
  {
    id: "employee",
    username: "e",
    password: demoPassword("e"),
    role: "employee",
    staffId: 13,
    managerId: "manager",
    scopeType: "self",
    scopeIds: ["employee"],
    areaId: "area-1",
    practiceId: "practice-harley",
    displayName: "Emma Employee",
    ...leaveDefaults,
    hrProfile: makeProfile("HR Hub Employee", "Southall"),
    email: "emma.employee@verbilo.co.uk",
    phoneExtension: "240",
    dateOfBirth: "1996-11-12",
    gender: "female",
    startDate: "2024-04-08",
    bio: "Hub team member at Southall.",
    qualifications: [],
    languages: ["English"],
    documents: adminDocs,
    isOnline: true,
  },
  {
    id: "associate-dentist",
    username: "ad",
    password: demoPassword("ad"),
    role: "associateDentist",
    staffId: 14,
    managerId: "manager",
    scopeType: "self",
    scopeIds: ["associate-dentist"],
    areaId: "area-1",
    practiceId: "practice-harley",
    teamId: "team-clinical-harley",
    displayName: "Dr. Amir Dentist",
    ...leaveDefaults,
    hrProfile: makeProfile("Associate Dentist", "Southall"),
    email: "amir.dentist@verbilo.co.uk",
    phoneExtension: "223",
    dateOfBirth: "1987-09-15",
    gender: "male",
    startDate: "2021-11-29",
    gdcNumber: "211485",
    gdcType: "Dentist",
    gdcRenewal: "2026-12-31",
    bio: "Associate Dentist at Southall. Mix of general dentistry with a growing cosmetic caseload.",
    qualifications: ["BDS University of Manchester", "MJDF RCS (Eng)"],
    languages: ["English", "Arabic"],
    documents: fullDocs,
    isOnline: false,
  },
  {
    id: "treatment-coordinator",
    username: "tc",
    password: demoPassword("tc"),
    role: "treatmentCoordinator",
    staffId: 15,
    managerId: "manager",
    scopeType: "self",
    scopeIds: ["treatment-coordinator"],
    areaId: "area-1",
    practiceId: "practice-harley",
    displayName: "Tara Coordinator",
    ...leaveDefaults,
    hrProfile: makeProfile("Treatment Coordinator", "Southall"),
    email: "tara.coordinator@verbilo.co.uk",
    phoneExtension: "241",
    dateOfBirth: "1993-04-02",
    gender: "female",
    startDate: "2022-05-09",
    bio: "Treatment Coordinator at Southall. Bridges the gap between the clinician's plan and the patient's next steps.",
    qualifications: ["Treatment Coordination Diploma"],
    languages: ["English"],
    documents: adminDocs,
    isOnline: true,
  },
  {
    id: "area-manager-2",
    username: "a2",
    password: demoPassword("a2"),
    role: "areaManager",
    staffId: 16,
    managerId: "managers-manager",
    scopeType: "area",
    scopeIds: ["area-2"],
    areaId: "area-2",
    displayName: "Adam Area Two",
    ...leaveDefaults,
    hrProfile: makeProfile("Area Manager - Area 2", "London, Manchester, Birmingham"),
    email: "adam.area@verbilo.co.uk",
    phoneExtension: "301",
    dateOfBirth: "1984-06-23",
    gender: "male",
    startDate: "2019-11-12",
    bio: "Area Manager for Area 2 (London, Manchester, Birmingham). Spends most of his week on a train.",
    qualifications: ["BA Business Management"],
    languages: ["English"],
    documents: adminDocs,
    isOnline: true,
  },
  {
    id: "practice-manager-area-2",
    username: "pm2",
    password: demoPassword("pm2"),
    role: "practiceManager",
    staffId: 17,
    managerId: "area-manager-2",
    scopeType: "practice",
    scopeIds: ["practice-camden"],
    areaId: "area-2",
    practiceId: "practice-camden",
    displayName: "Priya Practice Two",
    ...leaveDefaults,
    hrProfile: makeProfile("Practice Manager", "London"),
    email: "priya.practice@verbilo.co.uk",
    phoneExtension: "310",
    dateOfBirth: "1989-10-04",
    gender: "female",
    startDate: "2021-03-22",
    bio: "Practice Manager at London. Brought up through reception and dental nursing - knows every part of the practice.",
    qualifications: ["Level 4 Dental Practice Management", "NEBDN National Diploma"],
    languages: ["English", "Tamil"],
    documents: adminDocs,
    isOnline: false,
  },
  {
    id: "area-2-employee",
    username: "e2",
    password: demoPassword("e2"),
    role: "employee",
    staffId: 18,
    managerId: "practice-manager-area-2",
    scopeType: "self",
    scopeIds: ["area-2-employee"],
    areaId: "area-2",
    practiceId: "practice-camden",
    displayName: "Elliot Employee Two",
    ...leaveDefaults,
    hrProfile: makeProfile("HR Hub Employee", "London"),
    email: "elliot.employee@verbilo.co.uk",
    phoneExtension: "340",
    dateOfBirth: "1997-05-19",
    gender: "male",
    startDate: "2024-04-08",
    bio: "Hub team member at London.",
    qualifications: [],
    languages: ["English"],
    documents: adminDocs,
    isOnline: true,
  },
];
